### ISSUE TITLE
android-native: errors when using --from argument

### ISSUE THREAD

**Issue by JeriXNet** [KTXSoftware/khamake#10]
I run khamake like this
```
node Kha/make -t android-native --from path/to/android/native/build
```
And I get plenty of errors similar to this:
```
FC: cannot open PATH/TO/PRJ/KHA/KORE/SOURCES/KORE/NETWORK/SOCKET.H - No such file or folder
```

**Comment by RobDangerous** [comment]
Uh, shouldn't this be --to instead of --from?

**Comment by JeriXNet** [comment]
Actually I've already forgotten what was the case and how I thought it should work :(
Maybe we should we close the issue?

**Comment by RobDangerous** [comment]
Okidoki. Whatever it was, it's probably fixed.
