### ISSUE TITLE
html5 target and CDN cache compatibility

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/khamake#13]
Currently khamake use the Assets path as they are.
This means that the use of CDN (Content Delivery Network) would cache the assets even if they changed.

One solution to that is to generate a checksum string and append it to the asset path name.
Since khamake already contain a project.kha format with named asset. Khamake could generate such checksum and add it the asset name with the propper mapping in the generated project.kha.

A checksum should also be generated and appended to the kha.js and project.kha file names. This way CDN will be able to cache the kha game and its assets when they do not change and would not cache them if they change. This also allow efficient caching by browser by settign the server to tell the browser to cache the files as long as they can

**Comment by RobDangerous** [comment]
Cool idea, will do.

**Comment by wighawag** [comment]
any plan to work on this ?

Else I was thinking to use khafile to do it for me in the mean time

Is it supported / future proof to use 
```
project.assets.push({
  name: name,
  file: f,
  type: type
});
```

for adding assets with manual names and types

or do you plan to add another method for that ?

**Comment by RobDangerous** [comment]
Not future proof, will show another method for that at wwx.

**Comment by RobDangerous** [comment]
Hey, you fixed this, right?

**Comment by wighawag** [comment]
Yes, except that "kha.js" name is unchanged. But since this is anyway in control of the html page, this is fine.

**Comment by RobDangerous** [comment]
Okidoki!
