### ISSUE TITLE
embedflashassets fails on 15.8.0

### ISSUE THREAD

**Issue by Tezar** [KTXSoftware/khamake#14]
Trying to embed flash assets now fails (using haxelib version 15.8.0)

Steps to recreate:
1. clone kha empty project
2. try to run `haxelib run kha build flash --embedflashassets`

Fails on:
```
...\haxe\lib\kha\15,8,0\Tools\khamake\FlashExporter.js:26
        filename = filename.replaceAll('.', '_');
                            ^
TypeError: undefined is not a function
```

It seems, that at some point filename doesn't contain string but object `{path : "./project.kha"}` (or similar, writing that from memory, test dump is long gone...)

Falling back to 15.7.3 solves the problem.

**Comment by RobDangerous** [comment]
Solved in 15.10 (coming tonight).
