### ISSUE TITLE
Unity Backend

### ISSUE THREAD

**Issue by matt456** [KTXSoftware/khamake#16]
The unity backend has a bunch of errors mainly around shader compilation through khamake and then in the unity backend blob loading.

I've been patching as best I can, can someone supply me an older unity build folder for a project that actually works under unity, so I can finish patching the latest toolchains so they work and put it all in a pull request?

Cheers,
Matt

**Comment by RobDangerous** [comment]
AFAIK it's all working fine. Please reopen if you still have problems with the Unity export.
