### ISSUE TITLE
issues using haxelib libraries

### ISSUE THREAD

**Issue by sh-dave** [KTXSoftware/khamake#18]
hello robert,

i have a couple of issues using external libraries with kha.

1)  detection of the haxelib library path doesn't work for me (hardcoded to be 'lib' in the haxe installation folder) ```var libpath = pathlib.join(process.env.HAXEPATH, 'lib', libname.toLowerCase());```

it probably would be better to run ```haxelib config``` and use the output as basepath?

2) after i copied my libraries folder to the haxe installation i tried again. libraries still couldn't be found.
i have a git version of some library, so the ```.current``` file contains `dev`, and the ```.dev``` file in turn contains the correct folder of the git clone.

3) so i deleted ```.current``` and it picks up the ```.dev``` file ... still doesn't work.
the problem is, the library doesn't have a ```Sources``` folder, but ```src``` as it's specified in the haxelib.json:classpath property

4) copied src folder to Sources folder .. still doesn't work.
the library depends on another haxelib library (haxelib.json:dependencies property)

5) added all dependencies manually ... still doesn't work.
the libraries contain an ```extraParams.hxml``` that adds compiler flags (--macro) in this case, that don't get picked up by khamake

6) added the --macro's to the flashdevelop project file ... finally works! (well until i have to rebuild the project files)

now is it me being stupid, or is the whole haxelib integration not really supported by khamake?

**Comment by RobDangerous** [comment]
Support for haxelib libraries is very basic. But it looks like you've built a very nice test case. May I ask which libraries you are trying to use?

**Comment by sh-dave** [comment]
[tink_core](https://github.com/haxetink/tink_core) and [tink_lang](https://github.com/haxetink/tink_lang)

tink_lang is the one that starts the dependency chain
```
tink_lang (+ extraParams.hxml)
    => tink_syntaxhub (+ extraParams.hxml)
        => tink_priority
        => tink_macro
            => tink_core
```

**Comment by RobDangerous** [comment]
Added all of that. Can you give it a go?

**Comment by sh-dave** [comment]
Other than #26 it's looking good :smiley:

**Comment by RobDangerous** [comment]
Cool. #26 is merged so I'm closing this.
