### ISSUE TITLE
Debugging issue with generated FlashDevelop Project File (Flash Target)

### ISSUE THREAD

**Issue by sh-dave** [KTXSoftware/khamake#19]
Hello Robert,

i encounter issues with the generated FD project file for the flash target (FlashDevelop build 5.0.2.2). Kha is added via git submodule.

* Kha sources are added with an absolute path
* Kha sources are actually in a 'Kha' folder (uppercase K), 

(Additional libraries in the project.kha file are added with relative paths and are debuggable)

```
<classpaths>
    <class path="..\Sources" />
    <class path="e:\projects\myproject\kha\Sources" />
    <class path="e:\projects\myproject\kha\Backends\Flash" />
    <class path="..\Libraries\somelib1\Sources" />
    <class path="..\Libraries\somelib2\Sources" />
</classpaths>
```

This somehow breaks the ability to debug in FD. Breakpoints in Kha source files aren't hit, and doubleclicking logged exceptions/errors in the results panel fails to jump to the correct line in the files. The debugger always jumps to line 1.

Classpath | Test | Result
-------- | ------- | ---
```<class path="e:\projects\myproject\kha\Sources" />``` | original | fail
```<class path="..\kha\Sources" />``` | relative path | fail
```<class path="e:\projects\myproject\Kha\Sources" />``` | correct case | fail
```<class path="..\Kha\Sources" />```  | relative path + case | ok :smile:

**Comment by RobDangerous** [comment]
Hi Dave!
What is the exact khamake call you use? Just node Kha/make flash?

**Comment by sh-dave** [comment]
node kha/make -t flash

**Comment by RobDangerous** [comment]
Oh, can reproduce easily. Kinda weird, cause it didn't break debugging for me.

**Comment by sh-dave** [comment]
just noticed, when i use ```node Kha/make -t flash``` (uppercase K), the classpath is also added as uppercase K

**Comment by RobDangerous** [comment]
The small k big K thing is ok I think. Node reports the exec dir like that and it kinda makes sense.
