### ISSUE TITLE
Improvement: windows test scripts (MSBuild)

### ISSUE THREAD

**Issue by JeriXNet** [KTXSoftware/khamake#2]
I've made [this simple scripts](https://gist.github.com/JeriXNet/f19ac00018b9bf21447c) for quick windows testing from FD by hitting F5.
For now I just copy them in other script, that also run node Kha/make windows.
Maybe they should be integrated in khamake?

**Comment by RobDangerous** [comment]
This is now directly integrated in khamake with the --compile and --run options. Thanks!
