### ISSUE TITLE
html5 export hardcoded to a size of 800x600

### ISSUE THREAD

**Issue by jamiltron** [KTXSoftware/khamake#21]
https://github.com/KTXSoftware/khamake/blob/master/main.js#L357

It would be nice to be able to customize this.

**Comment by wighawag** [comment]
Actually on html5 the size of the canvas is determined by the html/css
You can modify build/html5/index.html to have the size you want. The one I use to have fullscreen mobile game is the following : https://github.com/wighawag/khamake/blob/allow_own_template/Data/html5/fullWindow.html


you can remove the div trace if you want the haxe trace to be shown in the browser console
