### ISSUE TITLE
Warning message appears during build

### ISSUE THREAD

**Issue by buckle2000** [KTXSoftware/khamake#55]
> 'webkitMovementX' is deprecated. Please use 'movementX' instead.
> 'webkitMovementY' is deprecated. Please use 'movementY' instead.

**Comment by RobDangerous** [comment]
After the build, right? In Kode Studio's console? That should already be fixed in the latest Kha revision but still have to test and merge into Kode Studio.

**Comment by buckle2000** [comment]
right

**Comment by buckle2000** [comment]
Another problem, the title of the window doesn't change. It is always "New Project".

**Comment by RobDangerous** [comment]
That should be the title as set in the khafile, isn't it?

**Comment by buckle2000** [comment]
You are right, but what is the use of `title` below:
> 		System.init({title: "This is a title", width: 1024, height: 768}, function () {

**Comment by RobDangerous** [comment]
That's used by targets which can change the window title dynamically (typically desktop targets). Same for width and height. The Kode Studio debugger doesn't support any dynamic changes of window parameters (but I know it's confusing so will probably make that an option).

**Comment by RobDangerous** [comment]
All fixed.
