### ISSUE TITLE
khafile should support async calls

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/khamake#57]
This has been discussed in the past on the irc channel. It would be good that instead of a return statement for the project in khafile, we would call instead  callback passing in the project.

```
done(project);
```
instead of 
```
return project;
```

This ways khafile would support asynchronous operations 

This would also solve the linting error due to returning something while outside of the scope of a function

**Comment by RobDangerous** [comment]
Hey, I implemented this. It's `resolve(project);`
