### ISSUE TITLE
Passing haxe compilation arguments

### ISSUE THREAD

**Issue by skylerparr** [KTXSoftware/khamake#62]
I'm trying to define a haxe compilation flag for conditional compilation. I added to my khafile.js project.addDefine("stuff"); but it doesn't seem to take an effect. Is this not the correct use case for addDefine? is there another method that I should call? I'm using the haxelib version of kha.

**Comment by sh-dave** [comment]
Not sure what you're trying to do, but may be the same as https://github.com/KTXSoftware/khamake/issues/45?

**Comment by RobDangerous** [comment]
Just regular Haxe defines, right? This is fixed on git.
New haxelib release when Haxe 3.3 proper is out.
