### ISSUE TITLE
Canvas size and System.init in html5/debug-html5

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/khamake#63]
In html5/debug-html5 the canvas in the index file is being generated with the size of 800x600 and in Main.hx System.init is being called with a size of 1024x768. Maybe all the references could use the size of the window in Kode Studio. This is when the size is not specified in khafile.js and khamake uses the default size.

**Comment by RobDangerous** [comment]
System.init can now define the size of the debug-html5 window.
No plans for changes in html5, canvas size will usually be defined by the host site. In general, width/height in System.init are to be treated as suggestions, only some systems can actually change width/height (mobile can't, for html5 it depends on the host).
