### ISSUE TITLE
khame server should not allow caching of files

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/khamake#8]
I have had weird behavior wiht my shaders until I cleared my cache.
If the shaders from 2 projects have the same names. or maybe if they are modified? the browser will get from the cache (which might be the shader from the other one

**Comment by RobDangerous** [comment]
That's not the server, that's the browser cache. Nothing I can do about that. Ctrl+F5 usually reloads without the cache.

**Comment by wighawag** [comment]
You can do by providing a no-cache header
like
````
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
```

**Comment by RobDangerous** [comment]
Ah, ok. Set an option in the used lib now which should help.
